C = mpicc
CFLAGS = -Wall -Wextra -lm

all: sieve1 sieve2 sieve3 sieve4

sieve1:
	@$(C) $(CFLAGS) -o sieve1 sieve1.c

sieve2:
	@$(C) $(CFLAGS) -o sieve2 sieve2.c

sieve3:
	@$(C) $(CFLAGS) -o sieve3 sieve3.c

sieve4:
	@$(C) $(CFLAGS) -o sieve4 sieve4.c

clean:
	@rm -f sieve1 sieve2 sieve3 sieve4