C = gcc
CFLAGS = -Wall -Wextra -fopenmp

part1-outer:
	@$(C) $(CFLAGS) -o part1-outer part1-outer.c

part1-inner:
	@$(C) $(CFLAGS) -o part1-inner part1-inner.c

part2:
	@$(C) $(CFLAGS) -o part2 part2.c

part3:
	@$(C) $(CFLAGS) -o part3 part3.c

clean:
	@rm -f part1-outer part1-inner part2 part3